name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: hash check
        run: ls && echo "$HASH"
        env:
          HASH: ${{ hashFiles('README.md') }}