name: GihHub Container Registry Test
run-name: Run by @${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the image'
        required: true
        type: string
    
defaults:
  run:
    shell: bash
env:
  IMAGE_NAME: test-image
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=v{{ inputs.version }}
            type=raw,value=latest
      - run: | 
          echo "TAGS $TAGS"
          echo "LABELS $LABELS"
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}
