name: Old
run-name: Run by @${{ github.actor }}
on: push
defaults:
  run:
    shell: bash
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "REPOSITORY_OWNER ${REPOSITORY_OWNER}"
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}

